import type {} from "../../dts/deno.window.d.ts";
AbortController
AbortController.prototype.abort
AbortController.prototype.signal
AbortSignal
AbortSignal.abort
AbortSignal.prototype.aborted
AbortSignal.prototype.addEventListener
AbortSignal.prototype.constructor
AbortSignal.prototype.dispatchEvent
AbortSignal.prototype.getParent
AbortSignal.prototype.onabort
AbortSignal.prototype.reason
AbortSignal.prototype.removeEventListener
AbortSignal.prototype.throwIfAborted
AggregateError
AggregateError.prototype.constructor
AggregateError.prototype.message
AggregateError.prototype.name
AggregateError.prototype.toString
Array
Array.from
Array.isArray
Array.of
Array.prototype.at
Array.prototype.concat
Array.prototype.copyWithin
Array.prototype.entries
Array.prototype.every
Array.prototype.fill
Array.prototype.filter
Array.prototype.find
Array.prototype.findIndex
Array.prototype.findLast
Array.prototype.findLastIndex
Array.prototype.flat
Array.prototype.flatMap
Array.prototype.forEach
Array.prototype.includes
Array.prototype.indexOf
Array.prototype.join
Array.prototype.keys
Array.prototype.lastIndexOf
Array.prototype.length
Array.prototype.map
Array.prototype.pop
Array.prototype.push
Array.prototype.reduce
Array.prototype.reduceRight
Array.prototype.reverse
Array.prototype.shift
Array.prototype.slice
Array.prototype.some
Array.prototype.sort
Array.prototype.splice
Array.prototype.toLocaleString
Array.prototype.toString
Array.prototype.unshift
Array.prototype.values
ArrayBuffer
ArrayBuffer.isView
ArrayBuffer.prototype.byteLength
ArrayBuffer.prototype.slice
Atomics.add
Atomics.and
Atomics.compareExchange
Atomics.exchange
Atomics.isLockFree
Atomics.load
Atomics.notify
Atomics.or
Atomics.store
Atomics.sub
Atomics.wait
Atomics.waitAsync
Atomics.xor
BigInt
BigInt.asIntN
BigInt.asUintN
BigInt.prototype.toLocaleString
BigInt.prototype.toString
BigInt.prototype.valueOf
BigInt64Array
BigInt64Array.BYTES_PER_ELEMENT
BigInt64Array.prototype.BYTES_PER_ELEMENT
BigInt64Array.prototype.at
BigInt64Array.prototype.buffer
BigInt64Array.prototype.byteLength
BigInt64Array.prototype.byteOffset
BigInt64Array.prototype.constructor
BigInt64Array.prototype.copyWithin
BigInt64Array.prototype.entries
BigInt64Array.prototype.every
BigInt64Array.prototype.fill
BigInt64Array.prototype.filter
BigInt64Array.prototype.find
BigInt64Array.prototype.findIndex
BigInt64Array.prototype.findLast
BigInt64Array.prototype.findLastIndex
BigInt64Array.prototype.forEach
BigInt64Array.prototype.includes
BigInt64Array.prototype.indexOf
BigInt64Array.prototype.join
BigInt64Array.prototype.keys
BigInt64Array.prototype.lastIndexOf
BigInt64Array.prototype.length
BigInt64Array.prototype.map
BigInt64Array.prototype.reduce
BigInt64Array.prototype.reduceRight
BigInt64Array.prototype.reverse
BigInt64Array.prototype.set
BigInt64Array.prototype.slice
BigInt64Array.prototype.some
BigInt64Array.prototype.sort
BigInt64Array.prototype.subarray
BigInt64Array.prototype.toLocaleString
BigInt64Array.prototype.toString
BigInt64Array.prototype.values
BigUint64Array
BigUint64Array.BYTES_PER_ELEMENT
BigUint64Array.prototype.BYTES_PER_ELEMENT
BigUint64Array.prototype.at
BigUint64Array.prototype.buffer
BigUint64Array.prototype.byteLength
BigUint64Array.prototype.byteOffset
BigUint64Array.prototype.constructor
BigUint64Array.prototype.copyWithin
BigUint64Array.prototype.entries
BigUint64Array.prototype.every
BigUint64Array.prototype.fill
BigUint64Array.prototype.filter
BigUint64Array.prototype.find
BigUint64Array.prototype.findIndex
BigUint64Array.prototype.findLast
BigUint64Array.prototype.findLastIndex
BigUint64Array.prototype.forEach
BigUint64Array.prototype.includes
BigUint64Array.prototype.indexOf
BigUint64Array.prototype.join
BigUint64Array.prototype.keys
BigUint64Array.prototype.lastIndexOf
BigUint64Array.prototype.length
BigUint64Array.prototype.map
BigUint64Array.prototype.reduce
BigUint64Array.prototype.reduceRight
BigUint64Array.prototype.reverse
BigUint64Array.prototype.set
BigUint64Array.prototype.slice
BigUint64Array.prototype.some
BigUint64Array.prototype.sort
BigUint64Array.prototype.subarray
BigUint64Array.prototype.toLocaleString
BigUint64Array.prototype.toString
BigUint64Array.prototype.values
Blob
Blob.prototype.arrayBuffer
Blob.prototype.size
Blob.prototype.slice
Blob.prototype.stream
Blob.prototype.text
Blob.prototype.type
Boolean
Boolean.prototype.toString
Boolean.prototype.valueOf
BroadcastChannel
BroadcastChannel.prototype.addEventListener
BroadcastChannel.prototype.close
BroadcastChannel.prototype.constructor
BroadcastChannel.prototype.dispatchEvent
BroadcastChannel.prototype.getParent
BroadcastChannel.prototype.name
BroadcastChannel.prototype.onmessage
BroadcastChannel.prototype.onmessageerror
BroadcastChannel.prototype.postMessage
BroadcastChannel.prototype.removeEventListener
ByteLengthQueuingStrategy
ByteLengthQueuingStrategy.prototype.highWaterMark
ByteLengthQueuingStrategy.prototype.size
CloseEvent
CloseEvent.prototype.AT_TARGET
CloseEvent.prototype.BUBBLING_PHASE
CloseEvent.prototype.CAPTURING_PHASE
CloseEvent.prototype.NONE
CloseEvent.prototype.bubbles
CloseEvent.prototype.cancelBubble
CloseEvent.prototype.cancelable
CloseEvent.prototype.code
CloseEvent.prototype.composed
CloseEvent.prototype.composedPath
CloseEvent.prototype.constructor
CloseEvent.prototype.currentTarget
CloseEvent.prototype.defaultPrevented
CloseEvent.prototype.eventPhase
CloseEvent.prototype.initialized
CloseEvent.prototype.preventDefault
CloseEvent.prototype.reason
CloseEvent.prototype.returnValue
CloseEvent.prototype.srcElement
CloseEvent.prototype.stopImmediatePropagation
CloseEvent.prototype.stopPropagation
CloseEvent.prototype.target
CloseEvent.prototype.timeStamp
CloseEvent.prototype.type
CloseEvent.prototype.wasClean
CountQueuingStrategy
CountQueuingStrategy.prototype.highWaterMark
CountQueuingStrategy.prototype.size
Crypto
Crypto.prototype.getRandomValues
Crypto.prototype.randomUUID
Crypto.prototype.subtle
CustomEvent
CustomEvent.prototype.AT_TARGET
CustomEvent.prototype.BUBBLING_PHASE
CustomEvent.prototype.CAPTURING_PHASE
CustomEvent.prototype.NONE
CustomEvent.prototype.bubbles
CustomEvent.prototype.cancelBubble
CustomEvent.prototype.cancelable
CustomEvent.prototype.composed
CustomEvent.prototype.composedPath
CustomEvent.prototype.constructor
CustomEvent.prototype.currentTarget
CustomEvent.prototype.defaultPrevented
CustomEvent.prototype.detail
CustomEvent.prototype.eventPhase
CustomEvent.prototype.initialized
CustomEvent.prototype.preventDefault
CustomEvent.prototype.returnValue
CustomEvent.prototype.srcElement
CustomEvent.prototype.stopImmediatePropagation
CustomEvent.prototype.stopPropagation
CustomEvent.prototype.target
CustomEvent.prototype.timeStamp
CustomEvent.prototype.type
DOMException
DOMException.ABORT_ERR
DOMException.DATA_CLONE_ERR
DOMException.DOMSTRING_SIZE_ERR
DOMException.HIERARCHY_REQUEST_ERR
DOMException.INDEX_SIZE_ERR
DOMException.INUSE_ATTRIBUTE_ERR
DOMException.INVALID_ACCESS_ERR
DOMException.INVALID_CHARACTER_ERR
DOMException.INVALID_MODIFICATION_ERR
DOMException.INVALID_NODE_TYPE_ERR
DOMException.INVALID_STATE_ERR
DOMException.NAMESPACE_ERR
DOMException.NETWORK_ERR
DOMException.NOT_FOUND_ERR
DOMException.NOT_SUPPORTED_ERR
DOMException.NO_DATA_ALLOWED_ERR
DOMException.NO_MODIFICATION_ALLOWED_ERR
DOMException.QUOTA_EXCEEDED_ERR
DOMException.SECURITY_ERR
DOMException.SYNTAX_ERR
DOMException.TIMEOUT_ERR
DOMException.TYPE_MISMATCH_ERR
DOMException.URL_MISMATCH_ERR
DOMException.VALIDATION_ERR
DOMException.WRONG_DOCUMENT_ERR
DOMException.prototype.ABORT_ERR
DOMException.prototype.DATA_CLONE_ERR
DOMException.prototype.DOMSTRING_SIZE_ERR
DOMException.prototype.HIERARCHY_REQUEST_ERR
DOMException.prototype.INDEX_SIZE_ERR
DOMException.prototype.INUSE_ATTRIBUTE_ERR
DOMException.prototype.INVALID_ACCESS_ERR
DOMException.prototype.INVALID_CHARACTER_ERR
DOMException.prototype.INVALID_MODIFICATION_ERR
DOMException.prototype.INVALID_NODE_TYPE_ERR
DOMException.prototype.INVALID_STATE_ERR
DOMException.prototype.NAMESPACE_ERR
DOMException.prototype.NETWORK_ERR
DOMException.prototype.NOT_FOUND_ERR
DOMException.prototype.NOT_SUPPORTED_ERR
DOMException.prototype.NO_DATA_ALLOWED_ERR
DOMException.prototype.NO_MODIFICATION_ALLOWED_ERR
DOMException.prototype.QUOTA_EXCEEDED_ERR
DOMException.prototype.SECURITY_ERR
DOMException.prototype.SYNTAX_ERR
DOMException.prototype.TIMEOUT_ERR
DOMException.prototype.TYPE_MISMATCH_ERR
DOMException.prototype.URL_MISMATCH_ERR
DOMException.prototype.VALIDATION_ERR
DOMException.prototype.WRONG_DOCUMENT_ERR
DOMException.prototype.code
DOMException.prototype.constructor
DOMException.prototype.message
DOMException.prototype.name
DOMException.prototype.toString
DataView
DataView.prototype.buffer
DataView.prototype.byteLength
DataView.prototype.byteOffset
DataView.prototype.getBigInt64
DataView.prototype.getBigUint64
DataView.prototype.getFloat32
DataView.prototype.getFloat64
DataView.prototype.getInt16
DataView.prototype.getInt32
DataView.prototype.getInt8
DataView.prototype.getUint16
DataView.prototype.getUint32
DataView.prototype.getUint8
DataView.prototype.setBigInt64
DataView.prototype.setBigUint64
DataView.prototype.setFloat32
DataView.prototype.setFloat64
DataView.prototype.setInt16
DataView.prototype.setInt32
DataView.prototype.setInt8
DataView.prototype.setUint16
DataView.prototype.setUint32
DataView.prototype.setUint8
Date
Date.UTC
Date.now
Date.parse
Date.prototype.getDate
Date.prototype.getDay
Date.prototype.getFullYear
Date.prototype.getHours
Date.prototype.getMilliseconds
Date.prototype.getMinutes
Date.prototype.getMonth
Date.prototype.getSeconds
Date.prototype.getTime
Date.prototype.getTimezoneOffset
Date.prototype.getUTCDate
Date.prototype.getUTCDay
Date.prototype.getUTCFullYear
Date.prototype.getUTCHours
Date.prototype.getUTCMilliseconds
Date.prototype.getUTCMinutes
Date.prototype.getUTCMonth
Date.prototype.getUTCSeconds
Date.prototype.getYear
Date.prototype.setDate
Date.prototype.setFullYear
Date.prototype.setHours
Date.prototype.setMilliseconds
Date.prototype.setMinutes
Date.prototype.setMonth
Date.prototype.setSeconds
Date.prototype.setTime
Date.prototype.setUTCDate
Date.prototype.setUTCFullYear
Date.prototype.setUTCHours
Date.prototype.setUTCMilliseconds
Date.prototype.setUTCMinutes
Date.prototype.setUTCMonth
Date.prototype.setUTCSeconds
Date.prototype.setYear
Date.prototype.toDateString
Date.prototype.toGMTString
Date.prototype.toISOString
Date.prototype.toJSON
Date.prototype.toLocaleDateString
Date.prototype.toLocaleString
Date.prototype.toLocaleTimeString
Date.prototype.toString
Date.prototype.toTimeString
Date.prototype.toUTCString
Date.prototype.valueOf
Deno.File
Deno.File.prototype.close
Deno.File.prototype.read
Deno.File.prototype.rid
Deno.args.length
Deno.build.arch
Deno.build.env
Deno.build.os
Deno.build.target
Deno.build.vendor
Deno.connect
Deno.connectTls
Deno.customInspect
Deno.cwd
Deno.env.delete
Deno.env.get
Deno.env.set
Deno.env.toObject
Deno.errors.AddrInUse
Deno.errors.AddrInUse.prototype.constructor
Deno.errors.AddrInUse.prototype.message
Deno.errors.AddrInUse.prototype.name
Deno.errors.AddrInUse.prototype.toString
Deno.errors.AddrNotAvailable
Deno.errors.AddrNotAvailable.prototype.constructor
Deno.errors.AddrNotAvailable.prototype.message
Deno.errors.AddrNotAvailable.prototype.name
Deno.errors.AddrNotAvailable.prototype.toString
Deno.errors.AlreadyExists
Deno.errors.AlreadyExists.prototype.constructor
Deno.errors.AlreadyExists.prototype.message
Deno.errors.AlreadyExists.prototype.name
Deno.errors.AlreadyExists.prototype.toString
Deno.errors.BadResource
Deno.errors.BadResource.prototype.constructor
Deno.errors.BadResource.prototype.message
Deno.errors.BadResource.prototype.name
Deno.errors.BadResource.prototype.toString
Deno.errors.BrokenPipe
Deno.errors.BrokenPipe.prototype.constructor
Deno.errors.BrokenPipe.prototype.message
Deno.errors.BrokenPipe.prototype.name
Deno.errors.BrokenPipe.prototype.toString
Deno.errors.Busy
Deno.errors.Busy.prototype.constructor
Deno.errors.Busy.prototype.message
Deno.errors.Busy.prototype.name
Deno.errors.Busy.prototype.toString
Deno.errors.ConnectionAborted
Deno.errors.ConnectionAborted.prototype.constructor
Deno.errors.ConnectionAborted.prototype.message
Deno.errors.ConnectionAborted.prototype.name
Deno.errors.ConnectionAborted.prototype.toString
Deno.errors.ConnectionRefused
Deno.errors.ConnectionRefused.prototype.constructor
Deno.errors.ConnectionRefused.prototype.message
Deno.errors.ConnectionRefused.prototype.name
Deno.errors.ConnectionRefused.prototype.toString
Deno.errors.ConnectionReset
Deno.errors.ConnectionReset.prototype.constructor
Deno.errors.ConnectionReset.prototype.message
Deno.errors.ConnectionReset.prototype.name
Deno.errors.ConnectionReset.prototype.toString
Deno.errors.Http
Deno.errors.Http.prototype.constructor
Deno.errors.Http.prototype.message
Deno.errors.Http.prototype.name
Deno.errors.Http.prototype.toString
Deno.errors.Interrupted
Deno.errors.Interrupted.prototype.constructor
Deno.errors.Interrupted.prototype.message
Deno.errors.Interrupted.prototype.name
Deno.errors.Interrupted.prototype.toString
Deno.errors.InvalidData
Deno.errors.InvalidData.prototype.constructor
Deno.errors.InvalidData.prototype.message
Deno.errors.InvalidData.prototype.name
Deno.errors.InvalidData.prototype.toString
Deno.errors.NotConnected
Deno.errors.NotConnected.prototype.constructor
Deno.errors.NotConnected.prototype.message
Deno.errors.NotConnected.prototype.name
Deno.errors.NotConnected.prototype.toString
Deno.errors.NotFound
Deno.errors.NotFound.prototype.constructor
Deno.errors.NotFound.prototype.message
Deno.errors.NotFound.prototype.name
Deno.errors.NotFound.prototype.toString
Deno.errors.NotSupported
Deno.errors.NotSupported.prototype.constructor
Deno.errors.NotSupported.prototype.message
Deno.errors.NotSupported.prototype.name
Deno.errors.NotSupported.prototype.toString
Deno.errors.PermissionDenied
Deno.errors.PermissionDenied.prototype.constructor
Deno.errors.PermissionDenied.prototype.message
Deno.errors.PermissionDenied.prototype.name
Deno.errors.PermissionDenied.prototype.toString
Deno.errors.TimedOut
Deno.errors.TimedOut.prototype.constructor
Deno.errors.TimedOut.prototype.message
Deno.errors.TimedOut.prototype.name
Deno.errors.TimedOut.prototype.toString
Deno.errors.UnexpectedEof
Deno.errors.UnexpectedEof.prototype.constructor
Deno.errors.UnexpectedEof.prototype.message
Deno.errors.UnexpectedEof.prototype.name
Deno.errors.UnexpectedEof.prototype.toString
Deno.errors.WriteZero
Deno.errors.WriteZero.prototype.constructor
Deno.errors.WriteZero.prototype.message
Deno.errors.WriteZero.prototype.name
Deno.errors.WriteZero.prototype.toString
Deno.inspect
Deno.listen
Deno.lstat
Deno.noColor
Deno.open
Deno.readDir
Deno.readFile
Deno.readTextFile
Deno.realPath
Deno.resolveDns
Deno.serveHttp
Deno.startTls
Deno.stat
Deno.test
Deno.upgradeWebSocket
Error
Error.captureStackTrace
Error.prepareStackTrace
Error.prototype.message
Error.prototype.name
Error.prototype.toString
Error.stackTraceLimit
ErrorEvent
ErrorEvent.prototype.AT_TARGET
ErrorEvent.prototype.BUBBLING_PHASE
ErrorEvent.prototype.CAPTURING_PHASE
ErrorEvent.prototype.NONE
ErrorEvent.prototype.bubbles
ErrorEvent.prototype.cancelBubble
ErrorEvent.prototype.cancelable
ErrorEvent.prototype.colno
ErrorEvent.prototype.composed
ErrorEvent.prototype.composedPath
ErrorEvent.prototype.constructor
ErrorEvent.prototype.currentTarget
ErrorEvent.prototype.defaultPrevented
ErrorEvent.prototype.error
ErrorEvent.prototype.eventPhase
ErrorEvent.prototype.filename
ErrorEvent.prototype.initialized
ErrorEvent.prototype.lineno
ErrorEvent.prototype.message
ErrorEvent.prototype.preventDefault
ErrorEvent.prototype.returnValue
ErrorEvent.prototype.srcElement
ErrorEvent.prototype.stopImmediatePropagation
ErrorEvent.prototype.stopPropagation
ErrorEvent.prototype.target
ErrorEvent.prototype.timeStamp
ErrorEvent.prototype.type
EvalError
EvalError.prototype.constructor
EvalError.prototype.message
EvalError.prototype.name
EvalError.prototype.toString
Event
Event.AT_TARGET
Event.BUBBLING_PHASE
Event.CAPTURING_PHASE
Event.NONE
Event.prototype.AT_TARGET
Event.prototype.BUBBLING_PHASE
Event.prototype.CAPTURING_PHASE
Event.prototype.NONE
Event.prototype.bubbles
Event.prototype.cancelBubble
Event.prototype.cancelable
Event.prototype.composed
Event.prototype.composedPath
Event.prototype.currentTarget
Event.prototype.defaultPrevented
Event.prototype.eventPhase
Event.prototype.initialized
Event.prototype.preventDefault
Event.prototype.returnValue
Event.prototype.srcElement
Event.prototype.stopImmediatePropagation
Event.prototype.stopPropagation
Event.prototype.target
Event.prototype.timeStamp
Event.prototype.type
EventTarget
EventTarget.prototype.addEventListener
EventTarget.prototype.dispatchEvent
EventTarget.prototype.getParent
EventTarget.prototype.removeEventListener
File
File.prototype.arrayBuffer
File.prototype.constructor
File.prototype.lastModified
File.prototype.name
File.prototype.size
File.prototype.slice
File.prototype.stream
File.prototype.text
File.prototype.type
FileReader
FileReader.DONE
FileReader.EMPTY
FileReader.LOADING
FileReader.prototype.DONE
FileReader.prototype.EMPTY
FileReader.prototype.LOADING
FileReader.prototype.abort
FileReader.prototype.addEventListener
FileReader.prototype.constructor
FileReader.prototype.dispatchEvent
FileReader.prototype.error
FileReader.prototype.getParent
FileReader.prototype.onabort
FileReader.prototype.onerror
FileReader.prototype.onload
FileReader.prototype.onloadend
FileReader.prototype.onloadstart
FileReader.prototype.onprogress
FileReader.prototype.readAsArrayBuffer
FileReader.prototype.readAsBinaryString
FileReader.prototype.readAsDataURL
FileReader.prototype.readAsText
FileReader.prototype.readyState
FileReader.prototype.removeEventListener
FileReader.prototype.result
FinalizationRegistry
FinalizationRegistry.prototype.register
FinalizationRegistry.prototype.unregister
Float32Array
Float32Array.BYTES_PER_ELEMENT
Float32Array.prototype.BYTES_PER_ELEMENT
Float32Array.prototype.at
Float32Array.prototype.buffer
Float32Array.prototype.byteLength
Float32Array.prototype.byteOffset
Float32Array.prototype.constructor
Float32Array.prototype.copyWithin
Float32Array.prototype.entries
Float32Array.prototype.every
Float32Array.prototype.fill
Float32Array.prototype.filter
Float32Array.prototype.find
Float32Array.prototype.findIndex
Float32Array.prototype.findLast
Float32Array.prototype.findLastIndex
Float32Array.prototype.forEach
Float32Array.prototype.includes
Float32Array.prototype.indexOf
Float32Array.prototype.join
Float32Array.prototype.keys
Float32Array.prototype.lastIndexOf
Float32Array.prototype.length
Float32Array.prototype.map
Float32Array.prototype.reduce
Float32Array.prototype.reduceRight
Float32Array.prototype.reverse
Float32Array.prototype.set
Float32Array.prototype.slice
Float32Array.prototype.some
Float32Array.prototype.sort
Float32Array.prototype.subarray
Float32Array.prototype.toLocaleString
Float32Array.prototype.toString
Float32Array.prototype.values
Float64Array
Float64Array.BYTES_PER_ELEMENT
Float64Array.prototype.BYTES_PER_ELEMENT
Float64Array.prototype.at
Float64Array.prototype.buffer
Float64Array.prototype.byteLength
Float64Array.prototype.byteOffset
Float64Array.prototype.constructor
Float64Array.prototype.copyWithin
Float64Array.prototype.entries
Float64Array.prototype.every
Float64Array.prototype.fill
Float64Array.prototype.filter
Float64Array.prototype.find
Float64Array.prototype.findIndex
Float64Array.prototype.findLast
Float64Array.prototype.findLastIndex
Float64Array.prototype.forEach
Float64Array.prototype.includes
Float64Array.prototype.indexOf
Float64Array.prototype.join
Float64Array.prototype.keys
Float64Array.prototype.lastIndexOf
Float64Array.prototype.length
Float64Array.prototype.map
Float64Array.prototype.reduce
Float64Array.prototype.reduceRight
Float64Array.prototype.reverse
Float64Array.prototype.set
Float64Array.prototype.slice
Float64Array.prototype.some
Float64Array.prototype.sort
Float64Array.prototype.subarray
Float64Array.prototype.toLocaleString
Float64Array.prototype.toString
Float64Array.prototype.values
FormData
FormData.prototype.append
FormData.prototype.delete
FormData.prototype.entries
FormData.prototype.forEach
FormData.prototype.get
FormData.prototype.getAll
FormData.prototype.has
FormData.prototype.keys
FormData.prototype.set
FormData.prototype.values
Function
Function.prototype.apply
Function.prototype.arguments
Function.prototype.bind
Function.prototype.call
Function.prototype.caller
Function.prototype.length
Function.prototype.name
Function.prototype.toString
Headers
Headers.prototype.append
Headers.prototype.delete
Headers.prototype.entries
Headers.prototype.forEach
Headers.prototype.get
Headers.prototype.has
Headers.prototype.keys
Headers.prototype.set
Headers.prototype.values
Infinity
Int16Array
Int16Array.BYTES_PER_ELEMENT
Int16Array.prototype.BYTES_PER_ELEMENT
Int16Array.prototype.at
Int16Array.prototype.buffer
Int16Array.prototype.byteLength
Int16Array.prototype.byteOffset
Int16Array.prototype.constructor
Int16Array.prototype.copyWithin
Int16Array.prototype.entries
Int16Array.prototype.every
Int16Array.prototype.fill
Int16Array.prototype.filter
Int16Array.prototype.find
Int16Array.prototype.findIndex
Int16Array.prototype.findLast
Int16Array.prototype.findLastIndex
Int16Array.prototype.forEach
Int16Array.prototype.includes
Int16Array.prototype.indexOf
Int16Array.prototype.join
Int16Array.prototype.keys
Int16Array.prototype.lastIndexOf
Int16Array.prototype.length
Int16Array.prototype.map
Int16Array.prototype.reduce
Int16Array.prototype.reduceRight
Int16Array.prototype.reverse
Int16Array.prototype.set
Int16Array.prototype.slice
Int16Array.prototype.some
Int16Array.prototype.sort
Int16Array.prototype.subarray
Int16Array.prototype.toLocaleString
Int16Array.prototype.toString
Int16Array.prototype.values
Int32Array
Int32Array.BYTES_PER_ELEMENT
Int32Array.prototype.BYTES_PER_ELEMENT
Int32Array.prototype.at
Int32Array.prototype.buffer
Int32Array.prototype.byteLength
Int32Array.prototype.byteOffset
Int32Array.prototype.constructor
Int32Array.prototype.copyWithin
Int32Array.prototype.entries
Int32Array.prototype.every
Int32Array.prototype.fill
Int32Array.prototype.filter
Int32Array.prototype.find
Int32Array.prototype.findIndex
Int32Array.prototype.findLast
Int32Array.prototype.findLastIndex
Int32Array.prototype.forEach
Int32Array.prototype.includes
Int32Array.prototype.indexOf
Int32Array.prototype.join
Int32Array.prototype.keys
Int32Array.prototype.lastIndexOf
Int32Array.prototype.length
Int32Array.prototype.map
Int32Array.prototype.reduce
Int32Array.prototype.reduceRight
Int32Array.prototype.reverse
Int32Array.prototype.set
Int32Array.prototype.slice
Int32Array.prototype.some
Int32Array.prototype.sort
Int32Array.prototype.subarray
Int32Array.prototype.toLocaleString
Int32Array.prototype.toString
Int32Array.prototype.values
Int8Array
Int8Array.BYTES_PER_ELEMENT
Int8Array.prototype.BYTES_PER_ELEMENT
Int8Array.prototype.at
Int8Array.prototype.buffer
Int8Array.prototype.byteLength
Int8Array.prototype.byteOffset
Int8Array.prototype.constructor
Int8Array.prototype.copyWithin
Int8Array.prototype.entries
Int8Array.prototype.every
Int8Array.prototype.fill
Int8Array.prototype.filter
Int8Array.prototype.find
Int8Array.prototype.findIndex
Int8Array.prototype.findLast
Int8Array.prototype.findLastIndex
Int8Array.prototype.forEach
Int8Array.prototype.includes
Int8Array.prototype.indexOf
Int8Array.prototype.join
Int8Array.prototype.keys
Int8Array.prototype.lastIndexOf
Int8Array.prototype.length
Int8Array.prototype.map
Int8Array.prototype.reduce
Int8Array.prototype.reduceRight
Int8Array.prototype.reverse
Int8Array.prototype.set
Int8Array.prototype.slice
Int8Array.prototype.some
Int8Array.prototype.sort
Int8Array.prototype.subarray
Int8Array.prototype.toLocaleString
Int8Array.prototype.toString
Int8Array.prototype.values
Intl.Collator
Intl.Collator.prototype.compare
Intl.Collator.prototype.resolvedOptions
Intl.Collator.supportedLocalesOf
Intl.DateTimeFormat
Intl.DateTimeFormat.prototype.format
Intl.DateTimeFormat.prototype.formatRange
Intl.DateTimeFormat.prototype.formatRangeToParts
Intl.DateTimeFormat.prototype.formatToParts
Intl.DateTimeFormat.prototype.resolvedOptions
Intl.DateTimeFormat.supportedLocalesOf
Intl.DisplayNames
Intl.DisplayNames.prototype.of
Intl.DisplayNames.prototype.resolvedOptions
Intl.DisplayNames.supportedLocalesOf
Intl.ListFormat
Intl.ListFormat.prototype.format
Intl.ListFormat.prototype.formatToParts
Intl.ListFormat.prototype.resolvedOptions
Intl.ListFormat.supportedLocalesOf
Intl.Locale
Intl.Locale.prototype.baseName
Intl.Locale.prototype.calendar
Intl.Locale.prototype.caseFirst
Intl.Locale.prototype.collation
Intl.Locale.prototype.hourCycle
Intl.Locale.prototype.language
Intl.Locale.prototype.maximize
Intl.Locale.prototype.minimize
Intl.Locale.prototype.numberingSystem
Intl.Locale.prototype.numeric
Intl.Locale.prototype.region
Intl.Locale.prototype.script
Intl.Locale.prototype.toString
Intl.NumberFormat
Intl.NumberFormat.prototype.format
Intl.NumberFormat.prototype.formatToParts
Intl.NumberFormat.prototype.resolvedOptions
Intl.NumberFormat.supportedLocalesOf
Intl.PluralRules
Intl.PluralRules.prototype.resolvedOptions
Intl.PluralRules.prototype.select
Intl.PluralRules.supportedLocalesOf
Intl.RelativeTimeFormat
Intl.RelativeTimeFormat.prototype.format
Intl.RelativeTimeFormat.prototype.formatToParts
Intl.RelativeTimeFormat.prototype.resolvedOptions
Intl.RelativeTimeFormat.supportedLocalesOf
Intl.Segmenter
Intl.Segmenter.prototype.resolvedOptions
Intl.Segmenter.prototype.segment
Intl.Segmenter.supportedLocalesOf
Intl.getCanonicalLocales
Intl.v8BreakIterator
Intl.v8BreakIterator.prototype.adoptText
Intl.v8BreakIterator.prototype.breakType
Intl.v8BreakIterator.prototype.current
Intl.v8BreakIterator.prototype.first
Intl.v8BreakIterator.prototype.next
Intl.v8BreakIterator.prototype.resolvedOptions
Intl.v8BreakIterator.supportedLocalesOf
JSON.parse
JSON.stringify
Map
Map.prototype.clear
Map.prototype.delete
Map.prototype.entries
Map.prototype.forEach
Map.prototype.get
Map.prototype.has
Map.prototype.keys
Map.prototype.set
Map.prototype.size
Map.prototype.values
Math.E
Math.LN10
Math.LN2
Math.LOG10E
Math.LOG2E
Math.PI
Math.SQRT1_2
Math.SQRT2
Math.abs
Math.acos
Math.acosh
Math.asin
Math.asinh
Math.atan
Math.atan2
Math.atanh
Math.cbrt
Math.ceil
Math.clz32
Math.cos
Math.cosh
Math.exp
Math.expm1
Math.floor
Math.fround
Math.hypot
Math.imul
Math.log
Math.log10
Math.log1p
Math.log2
Math.max
Math.min
Math.pow
Math.random
Math.round
Math.sign
Math.sin
Math.sinh
Math.sqrt
Math.tan
Math.tanh
Math.trunc
MessageEvent
MessageEvent.prototype.AT_TARGET
MessageEvent.prototype.BUBBLING_PHASE
MessageEvent.prototype.CAPTURING_PHASE
MessageEvent.prototype.NONE
MessageEvent.prototype.bubbles
MessageEvent.prototype.cancelBubble
MessageEvent.prototype.cancelable
MessageEvent.prototype.composed
MessageEvent.prototype.composedPath
MessageEvent.prototype.constructor
MessageEvent.prototype.currentTarget
MessageEvent.prototype.defaultPrevented
MessageEvent.prototype.eventPhase
MessageEvent.prototype.initialized
MessageEvent.prototype.preventDefault
MessageEvent.prototype.returnValue
MessageEvent.prototype.source
MessageEvent.prototype.srcElement
MessageEvent.prototype.stopImmediatePropagation
MessageEvent.prototype.stopPropagation
MessageEvent.prototype.target
MessageEvent.prototype.timeStamp
MessageEvent.prototype.type
NaN
Navigator
Navigator.prototype.hardwareConcurrency
Number
Number.EPSILON
Number.MAX_SAFE_INTEGER
Number.MAX_VALUE
Number.MIN_SAFE_INTEGER
Number.MIN_VALUE
Number.NEGATIVE_INFINITY
Number.NaN
Number.POSITIVE_INFINITY
Number.isFinite
Number.isInteger
Number.isNaN
Number.isSafeInteger
Number.parseFloat
Number.parseInt
Number.prototype.toExponential
Number.prototype.toFixed
Number.prototype.toLocaleString
Number.prototype.toPrecision
Number.prototype.toString
Number.prototype.valueOf
Object
Object.assign
Object.create
Object.defineProperties
Object.defineProperty
Object.entries
Object.freeze
Object.fromEntries
Object.getOwnPropertyDescriptor
Object.getOwnPropertyDescriptors
Object.getOwnPropertyNames
Object.getOwnPropertySymbols
Object.getPrototypeOf
Object.hasOwn
Object.is
Object.isExtensible
Object.isFrozen
Object.isSealed
Object.keys
Object.preventExtensions
Object.prototype.__defineGetter__
Object.prototype.__defineSetter__
Object.prototype.__lookupGetter__
Object.prototype.__lookupSetter__
Object.prototype.hasOwnProperty
Object.prototype.isPrototypeOf
Object.prototype.propertyIsEnumerable
Object.prototype.toLocaleString
Object.prototype.toString
Object.prototype.valueOf
Object.seal
Object.setPrototypeOf
Object.values
Performance
Performance.prototype.clearMarks
Performance.prototype.clearMeasures
Performance.prototype.getEntries
Performance.prototype.getEntriesByName
Performance.prototype.getEntriesByType
Performance.prototype.mark
Performance.prototype.measure
Performance.prototype.now
Performance.prototype.toJSON
PerformanceEntry
PerformanceEntry.prototype.duration
PerformanceEntry.prototype.entryType
PerformanceEntry.prototype.name
PerformanceEntry.prototype.startTime
PerformanceEntry.prototype.toJSON
PerformanceMark
PerformanceMark.prototype.constructor
PerformanceMark.prototype.detail
PerformanceMark.prototype.duration
PerformanceMark.prototype.entryType
PerformanceMark.prototype.name
PerformanceMark.prototype.startTime
PerformanceMark.prototype.toJSON
PerformanceMeasure
PerformanceMeasure.prototype.constructor
PerformanceMeasure.prototype.detail
PerformanceMeasure.prototype.duration
PerformanceMeasure.prototype.entryType
PerformanceMeasure.prototype.name
PerformanceMeasure.prototype.startTime
PerformanceMeasure.prototype.toJSON
ProgressEvent
ProgressEvent.prototype.AT_TARGET
ProgressEvent.prototype.BUBBLING_PHASE
ProgressEvent.prototype.CAPTURING_PHASE
ProgressEvent.prototype.NONE
ProgressEvent.prototype.bubbles
ProgressEvent.prototype.cancelBubble
ProgressEvent.prototype.cancelable
ProgressEvent.prototype.composed
ProgressEvent.prototype.composedPath
ProgressEvent.prototype.constructor
ProgressEvent.prototype.currentTarget
ProgressEvent.prototype.defaultPrevented
ProgressEvent.prototype.eventPhase
ProgressEvent.prototype.initialized
ProgressEvent.prototype.preventDefault
ProgressEvent.prototype.returnValue
ProgressEvent.prototype.srcElement
ProgressEvent.prototype.stopImmediatePropagation
ProgressEvent.prototype.stopPropagation
ProgressEvent.prototype.target
ProgressEvent.prototype.timeStamp
ProgressEvent.prototype.type
Promise
Promise.all
Promise.allSettled
Promise.any
Promise.prototype.catch
Promise.prototype.finally
Promise.prototype.then
Promise.race
Promise.reject
Promise.resolve
Proxy
Proxy.revocable
RangeError
RangeError.prototype.constructor
RangeError.prototype.message
RangeError.prototype.name
RangeError.prototype.toString
ReadableByteStreamController
ReadableByteStreamController.prototype.byobRequest
ReadableByteStreamController.prototype.close
ReadableByteStreamController.prototype.desiredSize
ReadableByteStreamController.prototype.enqueue
ReadableByteStreamController.prototype.error
ReadableStream
ReadableStream.prototype.cancel
ReadableStream.prototype.getReader
ReadableStream.prototype.locked
ReadableStream.prototype.pipeThrough
ReadableStream.prototype.pipeTo
ReadableStream.prototype.tee
ReadableStream.prototype.values
ReadableStreamBYOBReader
ReadableStreamBYOBReader.prototype.cancel
ReadableStreamBYOBReader.prototype.closed
ReadableStreamBYOBReader.prototype.read
ReadableStreamBYOBReader.prototype.releaseLock
ReadableStreamBYOBRequest
ReadableStreamBYOBRequest.prototype.respond
ReadableStreamBYOBRequest.prototype.respondWithNewView
ReadableStreamBYOBRequest.prototype.view
ReadableStreamDefaultController
ReadableStreamDefaultController.prototype.close
ReadableStreamDefaultController.prototype.desiredSize
ReadableStreamDefaultController.prototype.enqueue
ReadableStreamDefaultController.prototype.error
ReadableStreamDefaultReader
ReadableStreamDefaultReader.prototype.cancel
ReadableStreamDefaultReader.prototype.closed
ReadableStreamDefaultReader.prototype.read
ReadableStreamDefaultReader.prototype.releaseLock
ReferenceError
ReferenceError.prototype.constructor
ReferenceError.prototype.message
ReferenceError.prototype.name
ReferenceError.prototype.toString
Reflect.apply
Reflect.construct
Reflect.defineProperty
Reflect.deleteProperty
Reflect.get
Reflect.getOwnPropertyDescriptor
Reflect.getPrototypeOf
Reflect.has
Reflect.isExtensible
Reflect.ownKeys
Reflect.preventExtensions
Reflect.set
Reflect.setPrototypeOf
RegExp
RegExp.$&
RegExp["$'"]
RegExp["$+"]
RegExp.$1
RegExp.$2
RegExp.$3
RegExp.$4
RegExp.$5
RegExp.$6
RegExp.$7
RegExp.$8
RegExp.$9
RegExp.$_
RegExp["$`"]
RegExp.input
RegExp.lastMatch
RegExp.lastParen
RegExp.leftContext
RegExp.prototype.compile
RegExp.prototype.dotAll
RegExp.prototype.exec
RegExp.prototype.flags
RegExp.prototype.global
RegExp.prototype.hasIndices
RegExp.prototype.ignoreCase
RegExp.prototype.multiline
RegExp.prototype.source
RegExp.prototype.sticky
RegExp.prototype.test
RegExp.prototype.toString
RegExp.prototype.unicode
RegExp.rightContext
Request
Request.prototype.arrayBuffer
Request.prototype.blob
Request.prototype.body
Request.prototype.bodyUsed
Request.prototype.clone
Request.prototype.formData
Request.prototype.headers
Request.prototype.json
Request.prototype.method
Request.prototype.redirect
Request.prototype.signal
Request.prototype.text
Request.prototype.url
Response
Response.error
Response.prototype.arrayBuffer
Response.prototype.blob
Response.prototype.body
Response.prototype.bodyUsed
Response.prototype.clone
Response.prototype.formData
Response.prototype.headers
Response.prototype.json
Response.prototype.ok
Response.prototype.redirected
Response.prototype.status
Response.prototype.statusText
Response.prototype.text
Response.prototype.type
Response.prototype.url
Response.redirect
Set
Set.prototype.add
Set.prototype.clear
Set.prototype.delete
Set.prototype.entries
Set.prototype.forEach
Set.prototype.has
Set.prototype.keys
Set.prototype.size
Set.prototype.values
SharedArrayBuffer
SharedArrayBuffer.prototype.byteLength
SharedArrayBuffer.prototype.slice
String
String.fromCharCode
String.fromCodePoint
String.prototype.anchor
String.prototype.at
String.prototype.big
String.prototype.blink
String.prototype.bold
String.prototype.charAt
String.prototype.charCodeAt
String.prototype.codePointAt
String.prototype.concat
String.prototype.endsWith
String.prototype.fixed
String.prototype.fontcolor
String.prototype.fontsize
String.prototype.includes
String.prototype.indexOf
String.prototype.italics
String.prototype.lastIndexOf
String.prototype.length
String.prototype.link
String.prototype.localeCompare
String.prototype.match
String.prototype.matchAll
String.prototype.normalize
String.prototype.padEnd
String.prototype.padStart
String.prototype.repeat
String.prototype.replace
String.prototype.replaceAll
String.prototype.search
String.prototype.slice
String.prototype.small
String.prototype.split
String.prototype.startsWith
String.prototype.strike
String.prototype.sub
String.prototype.substr
String.prototype.substring
String.prototype.sup
String.prototype.toLocaleLowerCase
String.prototype.toLocaleUpperCase
String.prototype.toLowerCase
String.prototype.toString
String.prototype.toUpperCase
String.prototype.trim
String.prototype.trimEnd
String.prototype.trimLeft
String.prototype.trimRight
String.prototype.trimStart
String.prototype.valueOf
String.raw
SubtleCrypto
SubtleCrypto.prototype.decrypt
SubtleCrypto.prototype.deriveBits
SubtleCrypto.prototype.deriveKey
SubtleCrypto.prototype.digest
SubtleCrypto.prototype.encrypt
SubtleCrypto.prototype.exportKey
SubtleCrypto.prototype.generateKey
SubtleCrypto.prototype.importKey
SubtleCrypto.prototype.sign
SubtleCrypto.prototype.unwrapKey
SubtleCrypto.prototype.verify
SubtleCrypto.prototype.wrapKey
Symbol
Symbol.asyncIterator
Symbol.for
Symbol.hasInstance
Symbol.isConcatSpreadable
Symbol.iterator
Symbol.keyFor
Symbol.match
Symbol.matchAll
Symbol.prototype.description
Symbol.prototype.toString
Symbol.prototype.valueOf
Symbol.replace
Symbol.search
Symbol.species
Symbol.split
Symbol.toPrimitive
Symbol.toStringTag
Symbol.unscopables
SyntaxError
SyntaxError.prototype.constructor
SyntaxError.prototype.message
SyntaxError.prototype.name
SyntaxError.prototype.toString
TextDecoder
TextDecoder.prototype.decode
TextDecoder.prototype.encoding
TextDecoder.prototype.fatal
TextDecoder.prototype.ignoreBOM
TextDecoderStream
TextDecoderStream.prototype.encoding
TextDecoderStream.prototype.fatal
TextDecoderStream.prototype.ignoreBOM
TextDecoderStream.prototype.readable
TextDecoderStream.prototype.writable
TextEncoder
TextEncoder.prototype.encode
TextEncoder.prototype.encodeInto
TextEncoder.prototype.encoding
TextEncoderStream
TextEncoderStream.prototype.encoding
TextEncoderStream.prototype.readable
TextEncoderStream.prototype.writable
TransformStream
TransformStream.prototype.readable
TransformStream.prototype.writable
TransformStreamDefaultController
TransformStreamDefaultController.prototype.desiredSize
TransformStreamDefaultController.prototype.enqueue
TransformStreamDefaultController.prototype.error
TransformStreamDefaultController.prototype.terminate
TypeError
TypeError.prototype.constructor
TypeError.prototype.message
TypeError.prototype.name
TypeError.prototype.toString
URIError
URIError.prototype.constructor
URIError.prototype.message
URIError.prototype.name
URIError.prototype.toString
URL
URL.createObjectURL
URL.prototype.hash
URL.prototype.host
URL.prototype.hostname
URL.prototype.href
URL.prototype.origin
URL.prototype.password
URL.prototype.pathname
URL.prototype.port
URL.prototype.protocol
URL.prototype.search
URL.prototype.searchParams
URL.prototype.toJSON
URL.prototype.toString
URL.prototype.username
URL.revokeObjectURL
URLPattern
URLPattern.prototype.exec
URLPattern.prototype.hash
URLPattern.prototype.hostname
URLPattern.prototype.password
URLPattern.prototype.pathname
URLPattern.prototype.port
URLPattern.prototype.protocol
URLPattern.prototype.search
URLPattern.prototype.test
URLPattern.prototype.username
URLSearchParams
URLSearchParams.prototype.append
URLSearchParams.prototype.delete
URLSearchParams.prototype.entries
URLSearchParams.prototype.forEach
URLSearchParams.prototype.get
URLSearchParams.prototype.getAll
URLSearchParams.prototype.has
URLSearchParams.prototype.keys
URLSearchParams.prototype.set
URLSearchParams.prototype.sort
URLSearchParams.prototype.toString
URLSearchParams.prototype.values
Uint16Array
Uint16Array.BYTES_PER_ELEMENT
Uint16Array.prototype.BYTES_PER_ELEMENT
Uint16Array.prototype.at
Uint16Array.prototype.buffer
Uint16Array.prototype.byteLength
Uint16Array.prototype.byteOffset
Uint16Array.prototype.constructor
Uint16Array.prototype.copyWithin
Uint16Array.prototype.entries
Uint16Array.prototype.every
Uint16Array.prototype.fill
Uint16Array.prototype.filter
Uint16Array.prototype.find
Uint16Array.prototype.findIndex
Uint16Array.prototype.findLast
Uint16Array.prototype.findLastIndex
Uint16Array.prototype.forEach
Uint16Array.prototype.includes
Uint16Array.prototype.indexOf
Uint16Array.prototype.join
Uint16Array.prototype.keys
Uint16Array.prototype.lastIndexOf
Uint16Array.prototype.length
Uint16Array.prototype.map
Uint16Array.prototype.reduce
Uint16Array.prototype.reduceRight
Uint16Array.prototype.reverse
Uint16Array.prototype.set
Uint16Array.prototype.slice
Uint16Array.prototype.some
Uint16Array.prototype.sort
Uint16Array.prototype.subarray
Uint16Array.prototype.toLocaleString
Uint16Array.prototype.toString
Uint16Array.prototype.values
Uint32Array
Uint32Array.BYTES_PER_ELEMENT
Uint32Array.prototype.BYTES_PER_ELEMENT
Uint32Array.prototype.at
Uint32Array.prototype.buffer
Uint32Array.prototype.byteLength
Uint32Array.prototype.byteOffset
Uint32Array.prototype.constructor
Uint32Array.prototype.copyWithin
Uint32Array.prototype.entries
Uint32Array.prototype.every
Uint32Array.prototype.fill
Uint32Array.prototype.filter
Uint32Array.prototype.find
Uint32Array.prototype.findIndex
Uint32Array.prototype.findLast
Uint32Array.prototype.findLastIndex
Uint32Array.prototype.forEach
Uint32Array.prototype.includes
Uint32Array.prototype.indexOf
Uint32Array.prototype.join
Uint32Array.prototype.keys
Uint32Array.prototype.lastIndexOf
Uint32Array.prototype.length
Uint32Array.prototype.map
Uint32Array.prototype.reduce
Uint32Array.prototype.reduceRight
Uint32Array.prototype.reverse
Uint32Array.prototype.set
Uint32Array.prototype.slice
Uint32Array.prototype.some
Uint32Array.prototype.sort
Uint32Array.prototype.subarray
Uint32Array.prototype.toLocaleString
Uint32Array.prototype.toString
Uint32Array.prototype.values
Uint8Array
Uint8Array.BYTES_PER_ELEMENT
Uint8Array.prototype.BYTES_PER_ELEMENT
Uint8Array.prototype.at
Uint8Array.prototype.buffer
Uint8Array.prototype.byteLength
Uint8Array.prototype.byteOffset
Uint8Array.prototype.constructor
Uint8Array.prototype.copyWithin
Uint8Array.prototype.entries
Uint8Array.prototype.every
Uint8Array.prototype.fill
Uint8Array.prototype.filter
Uint8Array.prototype.find
Uint8Array.prototype.findIndex
Uint8Array.prototype.findLast
Uint8Array.prototype.findLastIndex
Uint8Array.prototype.forEach
Uint8Array.prototype.includes
Uint8Array.prototype.indexOf
Uint8Array.prototype.join
Uint8Array.prototype.keys
Uint8Array.prototype.lastIndexOf
Uint8Array.prototype.length
Uint8Array.prototype.map
Uint8Array.prototype.reduce
Uint8Array.prototype.reduceRight
Uint8Array.prototype.reverse
Uint8Array.prototype.set
Uint8Array.prototype.slice
Uint8Array.prototype.some
Uint8Array.prototype.sort
Uint8Array.prototype.subarray
Uint8Array.prototype.toLocaleString
Uint8Array.prototype.toString
Uint8Array.prototype.values
Uint8ClampedArray
Uint8ClampedArray.BYTES_PER_ELEMENT
Uint8ClampedArray.prototype.BYTES_PER_ELEMENT
Uint8ClampedArray.prototype.at
Uint8ClampedArray.prototype.buffer
Uint8ClampedArray.prototype.byteLength
Uint8ClampedArray.prototype.byteOffset
Uint8ClampedArray.prototype.constructor
Uint8ClampedArray.prototype.copyWithin
Uint8ClampedArray.prototype.entries
Uint8ClampedArray.prototype.every
Uint8ClampedArray.prototype.fill
Uint8ClampedArray.prototype.filter
Uint8ClampedArray.prototype.find
Uint8ClampedArray.prototype.findIndex
Uint8ClampedArray.prototype.findLast
Uint8ClampedArray.prototype.findLastIndex
Uint8ClampedArray.prototype.forEach
Uint8ClampedArray.prototype.includes
Uint8ClampedArray.prototype.indexOf
Uint8ClampedArray.prototype.join
Uint8ClampedArray.prototype.keys
Uint8ClampedArray.prototype.lastIndexOf
Uint8ClampedArray.prototype.length
Uint8ClampedArray.prototype.map
Uint8ClampedArray.prototype.reduce
Uint8ClampedArray.prototype.reduceRight
Uint8ClampedArray.prototype.reverse
Uint8ClampedArray.prototype.set
Uint8ClampedArray.prototype.slice
Uint8ClampedArray.prototype.some
Uint8ClampedArray.prototype.sort
Uint8ClampedArray.prototype.subarray
Uint8ClampedArray.prototype.toLocaleString
Uint8ClampedArray.prototype.toString
Uint8ClampedArray.prototype.values
WeakMap
WeakMap.prototype.delete
WeakMap.prototype.get
WeakMap.prototype.has
WeakMap.prototype.set
WeakRef
WeakRef.prototype.deref
WeakSet
WeakSet.prototype.add
WeakSet.prototype.delete
WeakSet.prototype.has
WebAssembly.CompileError
WebAssembly.CompileError.prototype.constructor
WebAssembly.CompileError.prototype.message
WebAssembly.CompileError.prototype.name
WebAssembly.CompileError.prototype.toString
WebAssembly.Exception
WebAssembly.Exception.prototype.constructor
WebAssembly.Exception.prototype.message
WebAssembly.Exception.prototype.name
WebAssembly.Exception.prototype.toString
WebAssembly.Global
WebAssembly.Global.prototype.value
WebAssembly.Global.prototype.valueOf
WebAssembly.Instance
WebAssembly.Instance.prototype.exports
WebAssembly.LinkError
WebAssembly.LinkError.prototype.constructor
WebAssembly.LinkError.prototype.message
WebAssembly.LinkError.prototype.name
WebAssembly.LinkError.prototype.toString
WebAssembly.Memory
WebAssembly.Memory.prototype.buffer
WebAssembly.Memory.prototype.grow
WebAssembly.Module
WebAssembly.Module.customSections
WebAssembly.Module.exports
WebAssembly.Module.imports
WebAssembly.RuntimeError
WebAssembly.RuntimeError.prototype.constructor
WebAssembly.RuntimeError.prototype.message
WebAssembly.RuntimeError.prototype.name
WebAssembly.RuntimeError.prototype.toString
WebAssembly.Table
WebAssembly.Table.prototype.get
WebAssembly.Table.prototype.grow
WebAssembly.Table.prototype.length
WebAssembly.Table.prototype.set
WebAssembly.Tag
WebAssembly.WebAssembly.Exception.prototype.getArg
WebAssembly.WebAssembly.Exception.prototype.is
WebAssembly.WebAssembly.Exception.prototype.message
WebAssembly.WebAssembly.Exception.prototype.name
WebAssembly.compile
WebAssembly.compileStreaming
WebAssembly.instantiate
WebAssembly.instantiateStreaming
WebAssembly.validate
WebSocket
WebSocket.CLOSED
WebSocket.CLOSING
WebSocket.CONNECTING
WebSocket.OPEN
WebSocket.prototype.CLOSED
WebSocket.prototype.CLOSING
WebSocket.prototype.CONNECTING
WebSocket.prototype.OPEN
WebSocket.prototype.addEventListener
WebSocket.prototype.binaryType
WebSocket.prototype.bufferedAmount
WebSocket.prototype.close
WebSocket.prototype.constructor
WebSocket.prototype.dispatchEvent
WebSocket.prototype.extensions
WebSocket.prototype.getParent
WebSocket.prototype.onclose
WebSocket.prototype.onerror
WebSocket.prototype.onmessage
WebSocket.prototype.onopen
WebSocket.prototype.protocol
WebSocket.prototype.readyState
WebSocket.prototype.removeEventListener
WebSocket.prototype.send
WebSocket.prototype.url
Window
Window.prototype.addEventListener
Window.prototype.constructor
Window.prototype.dispatchEvent
Window.prototype.getParent
Window.prototype.removeEventListener
WritableStream
WritableStream.prototype.abort
WritableStream.prototype.close
WritableStream.prototype.getWriter
WritableStream.prototype.locked
WritableStreamDefaultController
WritableStreamDefaultController.prototype.error
WritableStreamDefaultController.prototype.signal
WritableStreamDefaultWriter
WritableStreamDefaultWriter.prototype.abort
WritableStreamDefaultWriter.prototype.close
WritableStreamDefaultWriter.prototype.closed
WritableStreamDefaultWriter.prototype.desiredSize
WritableStreamDefaultWriter.prototype.ready
WritableStreamDefaultWriter.prototype.releaseLock
WritableStreamDefaultWriter.prototype.write
addEventListener
atob
btoa
clearInterval
clearTimeout
console.assert
console.clear
console.count
console.countReset
console.debug
console.dir
console.dirxml
console.error
console.group
console.groupCollapsed
console.groupEnd
console.indentLevel
console.info
console.log
console.table
console.time
console.timeEnd
console.timeLog
console.trace
console.warn
crypto.constructor
crypto.getRandomValues
crypto.randomUUID
crypto.subtle
decodeURI
decodeURIComponent
dispatchEvent
encodeURI
encodeURIComponent
escape
eval
fetch
isFinite
isNaN
navigator.constructor
navigator.hardwareConcurrency
parseFloat
parseInt
performance.clearMarks
performance.clearMeasures
performance.constructor
performance.getEntries
performance.getEntriesByName
performance.getEntriesByType
performance.mark
performance.measure
performance.now
performance.toJSON
queueMicrotask
removeEventListener
setInterval
setTimeout
undefined
unescape
